### ISSUE TITLE
Error in the SpaceDebugDrawOptions initialization

### ISSUE THREAD

**Issue by nav9** [nav9/LeggedRobotPyMunk#2]
In the newer versions of PyMunk, there's some error in the `SpaceDebugDrawOptions` initialization. The error shows up as:
`TypeError: <lambda>() missing 1 required positional argument: 'a' Exception ignored from cffi callback <function SpaceDebugDrawOptions.__init__.<locals>.f6 at 0x7f3ce81114c0>: Traceback (most recent call last): File "/home/navin/.pyenv/versions/3.9.6/lib/python3.9/site-packages/pymunk/space_debug_draw_options.py", line 110, in f6 return self.color_for_shape(shape) File "/home/navin/.pyenv/versions/3.9.6/lib/python3.9/site-packages/pymunk/space_debug_draw_options.py", line 270, in color_for_shape return SpaceDebugColor(*shape.color)`  
  
I'm currently unaware of what causes the problem and it'll take some time to figure out. If you figure it out, please do let me know via the Discussions option or the Issues option of this GitHub project.

**Comment by nav9** [comment]
There was a need for adding an alpha value as per the new requirements `SpaceDebugColor(r=44.0, g=62.0, b=80.0, a=255.0)`. Adding it resolved the error.
